#!/bin/sh

# PROVIDE: ZSEcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# ZSEcoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable ZSEcoin service.
# ZSEcoin_config (path): Set to /usr/local/etc/ZSEcoin.conf by default.
# ZSEcoin_user:  The user account ZSEcoin daemon runs as. It uses 'root' user by default.
# ZSEcoin_group: The group account ZSEcoin daemon runs as. It uses 'wheel' group by default.
# ZSEcoin_datadir (str): Default to "/var/db/ZSEcoin". Base data directory.

. /etc/rc.subr

name=ZSEcoin
rcvar=ZSEcoin_enable

: ${ZSEcoin_enable:=NO}
: ${ZSEcoin_config=/usr/local/etc/ZSEcoin.conf}
: ${ZSEcoin_datadir=/var/db/ZSEcoin}
: ${ZSEcoin_user="root"}
: ${ZSEcoin_group="wheel"}

required_files=${ZSEcoin_config}
command=/usr/local/bin/ZSEcoind
ZSEcoin_chdir=${ZSEcoin_datadir}
pidfile="${ZSEcoin_datadir}/ZSEcoind.pid"
stop_cmd=ZSEcoin_stop
command_args="-conf=${ZSEcoin_config} -datadir=${ZSEcoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

ZSEcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${ZSEcoin_datadir}
	[ $? -eq 0 ] && chown -R ${ZSEcoin_user}:${ZSEcoin_group} ${ZSEcoin_datadir}
}

ZSEcoin_prestart()
{
	if [ ! -d "${ZSEcoin_datadir}/." ]; then
		ZSEcoin_create_datadir || return 1
	fi
}

ZSEcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

ZSEcoin_stop()
{
    ZSEcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${ZSEcoin_config} -datadir=${ZSEcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
